Kc/ar-147/specialization-rules
Miller-Media/mwp-rules pull request #4
Opened 2021-06-10 23:51 UTC by kcarwilemiller

2021-06-22 15:30 UTC, mike-mm requested changes
Identified a missing property check, a minor refactor opportunity, and had a question about the `getter` function return values.

I was hard-pressed to find anything else amiss. Great work!

2021-06-22 15:30 UTC, mike-mm commented on classes/Rule.php
> +
This is pretty similar to the code block in lines 1310-1319, the only difference being the key we're checking. It could warrant creating a distinct function to avoid repeating the code.

2021-06-22 15:30 UTC, mike-mm commented on includes/rules.core.maps.php
> +						}
Do these `getter` functions need to explicitly return a `null` or `false` value if all else fails?

2021-06-22 22:41 UTC, kcarwilemiller commented on assets/js/main.js
> +								var special_key = event.data.special_key;
The `event.data` property is guaranteed as that is provided by the window messaging api, so if `special_key` has not been provided, then at worst case `var special_key` is assigned the value `undefined`. jQuery would then produce an empty element set which would in effect make the rest of the code inside the `$.get` callback a non-op.

Net net, any developer trying to use the message event and omitting the required event property is not going to cause any javascript errors, but will undoubtedly not get the expected result and will need to troubleshoot anyway. I think we're good here.

2021-06-22 22:55 UTC, kcarwilemiller commented on includes/rules.core.maps.php
> +						}
Nope. The result of a function that doesn't return a value in PHP is inherently NULL, so it would be the same as returning NULL. Which in the case of a getter is the proper value to return if something couldn't be loaded.

I do agree that actually including a `return NULL` statement is arguably better form as it makes it clear of the intention to return NULL, but since these data maps are already be a bit unwieldy to look at, I'm ok with shaving LOC where possible.

2021-06-23 00:34 UTC, kcarwilemiller commented on classes/Rule.php
> +
Dried it up.

2021-06-23 12:04 UTC, mike-mm approved these changes
Dry as a desert, nice

2021-06-23 12:06 UTC, mike-mm commented on assets/js/main.js
> +								var special_key = event.data.special_key;
Got it, and agreed

2021-06-23 12:06 UTC, merged